In [2]:
import pandas as pd

In [3]:

#well= pd.read_csv('https://raw.githubusercontent.com/edisonc57/ML_Oil-and-gas/main/Data/well_18_ml_v1.csv',usecols=[0,5,7,17])
well= pd.read_csv('https://raw.githubusercontent.com/edisonc57/ML_Oil-and-gas/main/Data/well_18_ml_v1.csv')

In [4]:
well.head()

,wellName,DEPTH,CGR,CPERM,CPHI,DT,DTSM,Facies,GR,MSFL,NPHI,PEF,Perm_Buckles_UpAs,PHIE,RHOB,RT,SWE,ZONE_NAME,net_gross
0,A-18-00,852.857,4.91913,-9999.0,-9999.0000,74.5270,121.9698,1,33.3418,5.79568,0.079834,4.783249,0.931011,0.072167,2.74411,10.27150,0.737652,U.Asmari,gross
1,A-18-00,853.010,9.99433,-9999.0,-9999.0000,88.8155,141.6838,1,53.4034,2.36973,0.151655,4.399977,9.209792,0.146527,2.61065,2.98569,0.667624,U.Asmari,gross
2,A-18-00,853.162,20.56400,-9999.0,-9999.0000,99.0574,166.7016,5,72.0957,1.31614,0.231567,4.030700,1.601786,0.220162,2.47339,1.38781,0.643816,U.Asmari,gross
3,A-18-00,853.314,31.71550,-9999.0,-9999.0000,104.7870,182.5868,5,78.3783,1.20371,0.287493,3.732858,3.690761,0.276589,2.35818,1.22050,0.541710,U.Asmari,net
4,A-18-00,853.467,37.70880,-9999.0,0.4288,104.8980,185.0199,5,70.4172,1.42773,0.297283,3.520631,5.106259,0.301175,2.29512,1.55953,0.438343,U.Asmari,net

In [5]:
print(well.columns.values)

['wellName' 'DEPTH' 'CGR' 'CPERM' 'CPHI' 'DT' 'DTSM' 'Facies' 'GR' 'MSFL'
 'NPHI' 'PEF' 'Perm_Buckles_UpAs' 'PHIE' 'RHOB' 'RT' 'SWE' 'ZONE_NAME'
 'net_gross']

In [6]:
print(well.dtypes)

wellName              object
DEPTH                float64
CGR                  float64
CPERM                float64
CPHI                 float64
DT                   float64
DTSM                 float64
Facies                 int64
GR                   float64
MSFL                 float64
NPHI                 float64
PEF                  float64
Perm_Buckles_UpAs    float64
PHIE                 float64
RHOB                 float64
RT                   float64
SWE                  float64
ZONE_NAME             object
net_gross             object
dtype: object

Haga doble clic <b>aquí</b> para ver la solución.

<!-- Respuesta:

df_column=df[['NombreColumna']]
df_column.dtypes

-->

## <strong>Visualizar las estadísticas</strong>

In [7]:
well.shape

(1104, 19)

In [8]:
well.describe()

,DEPTH,CGR,CPERM,CPHI,DT,DTSM,Facies,GR,MSFL,NPHI,PEF,Perm_Buckles_UpAs,PHIE,RHOB,RT,SWE
count,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000
mean,936.905800,22.047920,-9209.272460,-7816.181810,-116.954717,228.850209,-3502.405797,33.949555,1.031004,0.285081,2.750928,-8755.816317,0.272541,-323.818885,1.384850,0.810867
std,48.591466,14.814058,3000.540084,4132.484386,1474.010579,79.061065,4775.055663,13.704293,1.875299,0.055071,0.624573,3304.355297,0.073681,1777.139458,3.565423,0.221122
min,852.857000,-1.820080,-9999.000000,-9999.000000,-9999.000000,112.175300,-9999.000000,12.375400,0.154607,0.007749,1.892353,-9999.000000,0.000100,-9999.000000,0.140714,0.095850
25%,894.881750,10.967600,-9999.000000,-9999.000000,80.797725,157.599425,-9999.000000,24.259025,0.320093,0.261320,2.148058,-9999.000000,0.245062,2.174965,0.284590,0.759468
50%,936.906000,19.478800,-9999.000000,-9999.000000,95.242200,196.850000,4.000000,30.111500,0.471789,0.288055,2.858473,-9999.000000,0.283678,2.306270,0.426273,0.871985
75%,978.930000,30.318275,-9999.000000,-9999.000000,119.451500,307.697350,5.000000,40.395600,0.790757,0.318572,3.071843,-9999.000000,0.325287,2.395563,0.802269,0.992932
max,1020.950000,77.795400,24967.240230,0.431600,177.691000,397.756500,5.000000,95.275700,18.304800,0.433466,5.259470,98.421860,0.400000,2.945620,44.607900,1.000000

In [9]:
well.describe(include=['object'])

       wellName ZONE_NAME net_gross
count      1104      1104      1104
unique        1         5         2
top     A-18-00      Ghar       net
freq       1104       580       794

In [10]:
well.describe(include="all")

,wellName,DEPTH,CGR,CPERM,CPHI,DT,DTSM,Facies,GR,MSFL,NPHI,PEF,Perm_Buckles_UpAs,PHIE,RHOB,RT,SWE,ZONE_NAME,net_gross
count,1104,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104,1104
unique,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2
top,A-18-00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ghar,net
freq,1104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,580,794
mean,NaN,936.905800,22.047920,-9209.272460,-7816.181810,-116.954717,228.850209,-3502.405797,33.949555,1.031004,0.285081,2.750928,-8755.816317,0.272541,-323.818885,1.384850,0.810867,NaN,NaN
std,NaN,48.591466,14.814058,3000.540084,4132.484386,1474.010579,79.061065,4775.055663,13.704293,1.875299,0.055071,0.624573,3304.355297,0.073681,1777.139458,3.565423,0.221122,NaN,NaN
min,NaN,852.857000,-1.820080,-9999.000000,-9999.000000,-9999.000000,112.175300,-9999.000000,12.375400,0.154607,0.007749,1.892353,-9999.000000,0.000100,-9999.000000,0.140714,0.095850,NaN,NaN
25%,NaN,894.881750,10.967600,-9999.000000,-9999.000000,80.797725,157.599425,-9999.000000,24.259025,0.320093,0.261320,2.148058,-9999.000000,0.245062,2.174965,0.284590,0.759468,NaN,NaN
50%,NaN,936.906000,19.478800,-9999.000000,-9999.000000,95.242200,196.850000,4.000000,30.111500,0.471789,0.288055,2.858473,-9999.000000,0.283678,2.306270,0.426273,0.871985,NaN,NaN
75%,NaN,978.930000,30.318275,-9999.000000,-9999.000000,119.451500,307.697350,5.000000,40.395600,0.790757,0.318572,3.071843,-9999.000000,0.325287,2.395563,0.802269,0.992932,NaN,NaN
max,NaN,1020.950000,77.795400,24967.240230,0.431600,177.691000,397.756500,5.000000,95.275700,18.304800,0.433466,5.259470,98.421860,0.400000,2.945620,44.607900,1.000000,NaN,NaN

In [11]:
Zone = well['ZONE_NAME'].value_counts().to_frame()
print(Zone)

           count
ZONE_NAME
Ghar         580
Dammam       245
U.Asmari     137
L.Asmari     119
Ghar C.R      23